### ISSUE TITLE
ヘッダー実装

### ISSUE THREAD

**Issue by dninomiya** [camp-team/team-training#2]
## PC

![image](https://user-images.githubusercontent.com/5842851/88472636-ff406e00-cf4f-11ea-9c66-795abc68ba36.png)

ドロップダウンもあります

![image](https://user-images.githubusercontent.com/5842851/88549370-2cc60e00-d05b-11ea-96d1-222a0a05c1bd.png)

## SP

SPの時はドロワーにしてください

![image](https://user-images.githubusercontent.com/5842851/88472638-09626c80-cf50-11ea-890b-b786bcadf604.png)

![image](https://user-images.githubusercontent.com/5842851/88472642-12ebd480-cf50-11ea-97bf-f5872f10e094.png)

**Comment by mihye1128** [comment]
@deerboy
お疲れ様です。
headerのマークアップにあたって、下記に質問事項をまとめました。
テキストにしたらボリュームが出てしまいました💦
お忙しいところ恐縮ですが、お手隙の際にご確認よろしくお願い致します。

- [x] （logo）画像orテキスト
- [x] （drawer）footerコンテンツ
- [x] （drawer）開閉アクション
- [x] （component）コンポーネントの命名


**（logo）画像orテキスト**
XDではロゴはテキストのままですが、実装時は差替を踏まえて画像にした方が良いでしょうか？

**（drawer）footerコンテンツ**
Drawerの中にfooterの内容も含まれますが、こちらはどのように対応致しましょうか？
masterマージ後に、footerを担当してくださった方のコード入れていただくという認識で組んでも良いのでしょうか？
あるいは、こちらで組んだ方が良いでしょうか？

**（drawer）開閉アクション**
ドロワーの表示は、アイコンがあるので良いとして、閉じるアクションは、「`drawer内のリンクのどこか`,`drawerの背景`をクリックした時」という認識でよろしいでしょうか？
AngularMaterialで実装したいですが、ここだけの為に入れるのは申し訳ないので、一旦Materialなしでチャレンジしてみます。
難しかったときは、次回勉強会の際にdrawer開閉の実装について、ライブコーディングをリクエストさせていただてもよろしいですか…？
（headerのissueでAngular的なチャレンジ要素、これしかないのに弱気ですみません💦）

**（component）コンポーネントの命名**
headerコンポーネントを作成しようと思うのですが、同じタスクを別ブランチで行う場合、やはりコンポーネント名も変えた方が良いのでしょうか？（今回の場合、既に`feature/2`ブランチでheaderコンポーネントがあるので。）

**Comment by mihye1128** [comment]
@komura-c さんのプルリクが既に出てるんですね！早い✨✨

**Comment by komura-c** [comment]
ありがとうございます！本来であればそういった確認をしなければですよね…参考になります！

**Comment by mihye1128** [comment]
いえいえ！私の方こそ、勉強になります。

私の場合、社内の案件であれば気になったら口頭で聞けるから、ここまできちんと確認しませんが、
コーディングだけ受注を受けた時は、手戻りが少ない方がいいので、少しでも気になるところは聞くようにしてます💦

**Comment by dninomiya** [comment]
@mihye1128 
ご確認ありがとうございます！

- （logo）テキスト
- （drawer）footerコンテンツ不要
- （drawer）開閉アクションあり
- （component）コンポーネントの命名はheaderでOKです！

最終的にお二人の作業はニアリーイコールになると思うので、僕の方でお互いのいけてる実装をマージして一つのヘッダーにしてマージします 😺

**Comment by mihye1128** [comment]
@deerboy 
お疲れ様です。
ご回答ありがとうございます！
かしこまりました！

> 僕の方でお互いのいけてる実装をマージして一つのヘッダーにしてマージします 😺

かしこまりました！

**Comment by mihye1128** [comment]
font-styleの指定が抜けていたため、修正します。
