### ISSUE TITLE
記事詳細画面のコメントコンポーネント実装

### ISSUE THREAD

**Issue by dninomiya** [camp-team/team-training#26]
- 記事詳細画面のコメントコンポーネントを作成
- 記事には動画（サムネイル 画像）が再生ボタン付きで添付されるパターンが存在する
- 実際には動的にいろんな記事が入ってくるので、動画付きの記事が連続しても記事間の余白が等しく担保されることなどを確認する
- article-detail.component.html に設置

## PC

![image](https://user-images.githubusercontent.com/5842851/88776587-20f45c00-d1c1-11ea-86c2-584e54a76746.png)

## SP

![image](https://user-images.githubusercontent.com/5842851/88776687-3f5a5780-d1c1-11ea-8b8c-b2eaa1940e24.png)

**Comment by ghost** [comment]
記事の動画はvideoタグでの実装になりますか？
