### ISSUE TITLE
Formのはめ込み

### ISSUE THREAD

**Issue by chamaboy** [camp-team/team-training#43]
修正の対応お願いします！

## イメージ
![image](https://user-images.githubusercontent.com/63380386/92324239-dc3ec900-f07a-11ea-8651-86fc1bda2e60.png)

**Comment by ghost** [comment]
feat #43
以下、修正致しました。
ご確認よろしくお願いします！

![image](https://user-images.githubusercontent.com/63021280/92324852-8a00a680-f080-11ea-80e7-aa81dc201f63.png)
