### ISSUE TITLE
ニュースエリア実装

### ISSUE THREAD

**Issue by dninomiya** [camp-team/team-training#7]
## PC

![image](https://user-images.githubusercontent.com/5842851/88473755-86dfaa00-cf5b-11ea-8241-e4ed2a9804d7.png)

## SP

![image](https://user-images.githubusercontent.com/5842851/88473777-bb536600-cf5b-11ea-846d-178ee148d6ef.png)

**Comment by dninomiya** [comment]
@hk95 

見出しの余白がデザインと異なるので確認＆調整お願いします。

![image](https://user-images.githubusercontent.com/5842851/88491325-137e7c80-cfdd-11ea-979f-fb4e30d83e83.png)

また、要素全体にmax-heightがいることで下が詰まっています。ご確認よろしくお願いします。

![image](https://user-images.githubusercontent.com/5842851/88987431-d84bb880-d310-11ea-85eb-a10ecd20cfa0.png)

**Comment by hk95** [comment]
ご確認ありがとうございました。ご指摘の通り修正いたしましたので、再度ご確認お願いします。

**Comment by dninomiya** [comment]
@hk95 
PRお願いします！
