### ISSUE TITLE
ヒーローセクション

### ISSUE THREAD

**Issue by dninomiya** [camp-team/team-training#8]
## PC

![image](https://user-images.githubusercontent.com/5842851/88473779-c9a18200-cf5b-11ea-9329-28eee36e2427.png)

## SP

![image](https://user-images.githubusercontent.com/5842851/88473780-d0c89000-cf5b-11ea-8270-c2401a3fd98d.png)

**Comment by dninomiya** [comment]
#13
競合解決に不具合があったため再度PRをお願いします。

**Comment by dninomiya** [comment]
@yusukegunji 

レイアウトに収まるように高さや幅をフレキシブルに調整してもらいたいです。
また、見出しとテキスト間の余白などがデザインと異なるのでピクセルパーフェクトで調整して欲しいです。
（例えば見出しとボーダーの間が40pxになっていません）

![image](https://user-images.githubusercontent.com/5842851/88755587-71a58e00-d19c-11ea-8ffc-7ec11290078a.png)

**Comment by deerboy** [comment]
f
